// <auto-generated />
using AikaSeggs.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AikaSeggs.Database.Migrations
{
    [DbContext(typeof(AikaSeggsContext))]
    [Migration("20260111231823_InitialStoryDB")]
    partial class InitialStoryDB
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.11");

            modelBuilder.Entity("AikaSeggs.Database.Models.AccountDB", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("BattlePointValue")
                        .HasColumnType("INTEGER");

                    b.Property<int>("BattleSpeed")
                        .HasColumnType("INTEGER");

                    b.Property<int>("BgmVolume")
                        .HasColumnType("INTEGER");

                    b.Property<int>("CharacterMaxCount")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("EquipmentMaxCount")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Exp")
                        .HasColumnType("INTEGER");

                    b.Property<int>("FreeGem")
                        .HasColumnType("INTEGER");

                    b.Property<int>("IsBgmMute")
                        .HasColumnType("INTEGER");

                    b.Property<int>("IsSeMute")
                        .HasColumnType("INTEGER");

                    b.Property<int>("IsSkillAuto")
                        .HasColumnType("INTEGER");

                    b.Property<int>("IsVoiceMute")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ItemMaxCount")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Level")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MaxBattlePoint")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MaxStamina")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PaidGem")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("PlayerType")
                        .HasColumnType("INTEGER");

                    b.Property<string>("RegisterDate")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("SeVolume")
                        .HasColumnType("INTEGER");

                    b.Property<int>("StaminaValue")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SystemDate")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("TutorialEndDate")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("TutorialStep")
                        .HasColumnType("INTEGER");

                    b.Property<string>("UserCd")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("UserNameStatus")
                        .HasColumnType("INTEGER");

                    b.Property<string>("UserNameTextId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("UserText")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("VoiceVolume")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Accounts");
                });

            modelBuilder.Entity("AikaSeggs.Database.Models.CharacterDB", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("CharacterCd")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("CharacterId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("RegisterDate")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("UserCd")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("UserCd", "CharacterCd")
                        .IsUnique();

                    b.ToTable("Characters");
                });

            modelBuilder.Entity("AikaSeggs.Database.Models.StoryDB", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("IsRead")
                        .HasColumnType("INTEGER");

                    b.Property<int>("StoryId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("UserCd")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("UserCd", "StoryId")
                        .IsUnique();

                    b.ToTable("Stories");
                });

            modelBuilder.Entity("AikaSeggs.Database.Models.CharacterDB", b =>
                {
                    b.HasOne("AikaSeggs.Database.Models.AccountDB", "Account")
                        .WithMany("Characters")
                        .HasForeignKey("UserCd")
                        .HasPrincipalKey("UserCd")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Account");
                });

            modelBuilder.Entity("AikaSeggs.Database.Models.StoryDB", b =>
                {
                    b.HasOne("AikaSeggs.Database.Models.AccountDB", "Account")
                        .WithMany("Stories")
                        .HasForeignKey("UserCd")
                        .HasPrincipalKey("UserCd")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Account");
                });

            modelBuilder.Entity("AikaSeggs.Database.Models.AccountDB", b =>
                {
                    b.Navigation("Characters");

                    b.Navigation("Stories");
                });
#pragma warning restore 612, 618
        }
    }
}
