// <auto-generated />
using AikaSeggs.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AikaSeggs.Database.Migrations
{
    [DbContext(typeof(AikaSeggsContext))]
    partial class AikaSeggsContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.11");

            modelBuilder.Entity("AikaSeggs.Database.Models.AccountDB", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("BattlePointValue")
                        .HasColumnType("INTEGER");

                    b.Property<int>("BattleSpeed")
                        .HasColumnType("INTEGER");

                    b.Property<int>("BgmVolume")
                        .HasColumnType("INTEGER");

                    b.Property<int>("CharacterMaxCount")
                        .HasColumnType("INTEGER");

                    b.Property<int>("EquipmentMaxCount")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Exp")
                        .HasColumnType("INTEGER");

                    b.Property<int>("FreeGem")
                        .HasColumnType("INTEGER");

                    b.Property<int>("IsBgmMute")
                        .HasColumnType("INTEGER");

                    b.Property<int>("IsSeMute")
                        .HasColumnType("INTEGER");

                    b.Property<int>("IsSkillAuto")
                        .HasColumnType("INTEGER");

                    b.Property<int>("IsVoiceMute")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ItemMaxCount")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Level")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MaxBattlePoint")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MaxStamina")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PaidGem")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PlayerType")
                        .HasColumnType("INTEGER");

                    b.Property<string>("RegisterDate")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("SeVolume")
                        .HasColumnType("INTEGER");

                    b.Property<int>("StaminaValue")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SystemDate")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("TutorialEndDate")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("TutorialStep")
                        .HasColumnType("INTEGER");

                    b.Property<string>("UserCd")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("UserNameStatus")
                        .HasColumnType("INTEGER");

                    b.Property<string>("UserNameTextId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("UserText")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("VoiceVolume")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Accounts");
                });

            modelBuilder.Entity("AikaSeggs.Database.Models.CharacterDB", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("AbilityLevel1")
                        .HasColumnType("INTEGER");

                    b.Property<int>("AbilityLevel2")
                        .HasColumnType("INTEGER");

                    b.Property<int>("AbilityLevel3")
                        .HasColumnType("INTEGER");

                    b.Property<int>("AddAtk")
                        .HasColumnType("INTEGER");

                    b.Property<int>("AddDef")
                        .HasColumnType("INTEGER");

                    b.Property<int>("AddHp")
                        .HasColumnType("INTEGER");

                    b.Property<int>("AddRarity")
                        .HasColumnType("INTEGER");

                    b.Property<string>("AwakeIds")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("BattleCount")
                        .HasColumnType("INTEGER");

                    b.Property<string>("CharacterCd")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("CharacterId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("EquipmentProtectorCds")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("EquipmentWeaponCds")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("ExceedLimit")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ExceedLimitExp")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Exp")
                        .HasColumnType("INTEGER");

                    b.Property<int>("IsProtect")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Level")
                        .HasColumnType("INTEGER");

                    b.Property<string>("RegisterDate")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("SkillLevel")
                        .HasColumnType("INTEGER");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("UserId", "CharacterCd")
                        .IsUnique();

                    b.ToTable("Characters");
                });

            modelBuilder.Entity("AikaSeggs.Database.Models.DeckDB", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("CharacterCds")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("DeckId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("DeckName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("MemorialCd")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("UserId", "DeckId")
                        .IsUnique();

                    b.ToTable("Decks");
                });

            modelBuilder.Entity("AikaSeggs.Database.Models.EquipmentDB", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("EquipmentCd")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("EquipmentId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ExceedLimit")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ExceedLimitExp")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Exp")
                        .HasColumnType("INTEGER");

                    b.Property<int>("IsProtect")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Level")
                        .HasColumnType("INTEGER");

                    b.Property<string>("RegisterDate")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("UserId", "EquipmentCd")
                        .IsUnique();

                    b.ToTable("Equipment");
                });

            modelBuilder.Entity("AikaSeggs.Database.Models.ItemDB", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Count")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ItemId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("UserId", "ItemId")
                        .IsUnique();

                    b.ToTable("Items");
                });

            modelBuilder.Entity("AikaSeggs.Database.Models.MissionDB", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("ClearCount")
                        .HasColumnType("INTEGER");

                    b.Property<string>("MissionCd")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("MissionGroupId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MissionId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MissionType")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ReceiveCount")
                        .HasColumnType("INTEGER");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("UserId", "MissionId")
                        .IsUnique();

                    b.ToTable("Missions");
                });

            modelBuilder.Entity("AikaSeggs.Database.Models.QuestDB", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("ClearCount")
                        .HasColumnType("INTEGER");

                    b.Property<int>("IsUnlock")
                        .HasColumnType("INTEGER");

                    b.Property<int>("QuestId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("StageId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("UserId", "QuestId")
                        .IsUnique();

                    b.ToTable("Quests");
                });

            modelBuilder.Entity("AikaSeggs.Database.Models.CharacterDB", b =>
                {
                    b.HasOne("AikaSeggs.Database.Models.AccountDB", "Account")
                        .WithMany("Characters")
                        .HasForeignKey("UserId")
                        .HasPrincipalKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Account");
                });

            modelBuilder.Entity("AikaSeggs.Database.Models.DeckDB", b =>
                {
                    b.HasOne("AikaSeggs.Database.Models.AccountDB", "Account")
                        .WithMany("Decks")
                        .HasForeignKey("UserId")
                        .HasPrincipalKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Account");
                });

            modelBuilder.Entity("AikaSeggs.Database.Models.EquipmentDB", b =>
                {
                    b.HasOne("AikaSeggs.Database.Models.AccountDB", "Account")
                        .WithMany("Equipment")
                        .HasForeignKey("UserId")
                        .HasPrincipalKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Account");
                });

            modelBuilder.Entity("AikaSeggs.Database.Models.ItemDB", b =>
                {
                    b.HasOne("AikaSeggs.Database.Models.AccountDB", "Account")
                        .WithMany("Items")
                        .HasForeignKey("UserId")
                        .HasPrincipalKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Account");
                });

            modelBuilder.Entity("AikaSeggs.Database.Models.MissionDB", b =>
                {
                    b.HasOne("AikaSeggs.Database.Models.AccountDB", "Account")
                        .WithMany("Missions")
                        .HasForeignKey("UserId")
                        .HasPrincipalKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Account");
                });

            modelBuilder.Entity("AikaSeggs.Database.Models.QuestDB", b =>
                {
                    b.HasOne("AikaSeggs.Database.Models.AccountDB", "Account")
                        .WithMany("Quests")
                        .HasForeignKey("UserId")
                        .HasPrincipalKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Account");
                });

            modelBuilder.Entity("AikaSeggs.Database.Models.AccountDB", b =>
                {
                    b.Navigation("Characters");

                    b.Navigation("Decks");

                    b.Navigation("Equipment");

                    b.Navigation("Items");

                    b.Navigation("Missions");

                    b.Navigation("Quests");
                });
#pragma warning restore 612, 618
        }
    }
}
